name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ran-git0
          filename: metrics.svg

          base: header, metadata

          # use your custom template from your fork repo
          template: "@ran-terminal"
          setup_community_templates: "Ran-git0/metrics@master:ran-terminal+trust"

          # requested plugins
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "YOUR_STEAM_ID_64"
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_games_limit: 2
          plugin_steam_recent_games_limit: 2
          plugin_steam_achievements_limit: 3

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 8

          plugin_activity: yes
          plugin_activity_limit: 6
          plugin_activity_days: 14

          plugin_topics: yes
          plugin_topics_mode: starred
          plugin_topics_sort: starred
          plugin_topics_limit: 12

          plugin_gists: yes
          plugin_introduction: yes
          plugin_introduction_title: no
